dist: trusty
language: node_js
cache: npm
node_js:
  - "10"
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - ./runcheckendline.sh
  - npm run validate
  - npm run test:coverage
  - codeclimate-test-reporter < coverage/lcov.info